name: ppoulain-python
# channels priority
# see https://bioconda.github.io/
# conda-forge has highest prioriy
channels:
  - defaults
  - etetoolkit
  - bioconda
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - numpy
  - scipy
  - matplotlib
  - pandas
  - biopython
  - jupyterlab>=3
  - ipywidgets
  # Linters and formaters
  - pycodestyle
  - pydocstyle
  - pylint
  - black
  - ruff
  - nodejs
  # Tools
  - nbresuse
  - psutil
  # Jupyter archive
  # https://github.com/jupyterlab-contrib/jupyter-archive
  - jupyter-archive=3.3.4
  # for projects
  - pytest
  # Bokeh
  # https://docs.bokeh.org/en/latest/docs/user_guide/output/jupyter.html#jupyterlab
  - bokeh
  - jupyter_bokeh
  # plotly
  # https://plotly.com/python/getting-started/
  - plotly
  # Pillow
  # https://pillow.readthedocs.io/en/stable/installation.html
  - pillow
  # scikit-image
  # https://scikit-image.org/docs/stable/install.html
  - scikit-image
  # scikit-learn
  # https://scikit-learn.org/stable/install.html
  - scikit-learn
  # RDKit
  # https://scikit-learn.org/stable/install.html
  - rdkit
  # Requests
  # https://anaconda.org/conda-forge/requests
  - requests
  # Ete
  # http://etetoolkit.org/download/
  - ete3
  # BioPandas
  # http://rasbt.github.io/biopandas/installation/
  - biopandas
  # MDanalys
  - mdanalysis
  - pip:
    # watermark
    - watermark
    # streamlit
    - streamlit
    # Flask
    - Flask
    # nbqa : notebook quality control
    # https://nbqa.readthedocs.io/en/latest/index.html
    - nbqa
    # jupyterlab-fasta
    # https://github.com/jupyterlab/jupyter-renderers/tree/main/packages/fasta-extension
    - jupyterlab-fasta
