name: ppoulain-python-2021
# channels priority
# see https://bioconda.github.io/
# conda-forge has highest prioriy
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - numpy
  - scipy
  - matplotlib
  - pandas
  - biopython
  - jupyterlab>=3
  - ipywidgets
  - pycodestyle
  - pydocstyle
  - pylint
  - nodejs
  - nbresuse
  - psutil
  # for projects
  - pytest
  # Bokeh
  # https://docs.bokeh.org/en/latest/docs/installation.html
  - bokeh==2.2.2
  - jupyter_bokeh
  # plotly
  # https://plotly.com/python/getting-started/
  - plotly==5.3.0
  # Muscle
  # https://anaconda.org/bioconda/muscle
  - muscle
  # Pillow
  # https://pillow.readthedocs.io/en/stable/installation.html
  - pillow
  # scikit-image
  # https://scikit-image.org/docs/stable/install.html
  - scikit-image
  # scikit-learn
  # https://scikit-learn.org/stable/install.html
  - scikit-learn
  # RDKit
  # https://scikit-learn.org/stable/install.html
  - rdkit
  # Requests
  # https://anaconda.org/conda-forge/requests
  - requests
  - pip:
    # watermark
    - watermark
    # streamlit
    - streamlit